Overhaul bt wrapper script

diff --git a/scripts/bt b/scripts/bt
--- a/scripts/bt
+++ b/scripts/bt
@@ -1,38 +1,76 @@
 #!/bin/bash
-bluetoothctl power on
+
+DEVFILE=$HOME/.config/bt/devices
+
+# Power on bluetooth controller
+[[ `bluetoothctl show | rg "Powered" | awk '{print $2}'` == "yes" ]] || bluetoothctl power on
+
+# Load associative array with device name -> mac address
+IFS="\n"
+
+readarray -t a < "$DEVFILE"
+
+declare -A devices
+
+for e in ${a[@]}; do
+    k=`echo $e | awk '{print $1}'`
+    v=`echo $e | awk '{print $2}'`
+    devices+=( [$k]=$v )
+done
+
+has_dev() {
+    [[ ${devices[$1]+true} ]]
+}
+
+get_dev() {
+    if [[ -n $1 ]]; then
+        dev=$1
+    else
+        dev=`printf "%s\n" ${!devices[@]} | fzf --header="device menu" --info="hidden"`
+    fi
+    has_dev $dev || exit 0
+    echo $dev
+}
 
 
-dev=""
 case $1 in
-    ap)
-        dev="E4:90:FD:90:2B:52"
+    connect | con | c)
+            dev=`get_dev $2`
+            [[ -z $dev ]] && echo "Invalid device" && exit 1
+            mac=${devices[$dev]}
+            bluetoothctl connect $mac || exit 1
+            [[ $dev = "wacom" ]] && config-wacom
         ;;
-    wacom)
-        dev="E0:9F:2A:16:65:E4"
+    disconnect | discon | d)
+            dev=`get_dev $2`
+            [[ -z $dev ]] && echo "Invalid device" && exit 1
+            mac=${devices[$dev]}
+            bluetoothctl disconnect $mac || exit 1
+        ;;
+    toggle | t)
+        dev=`get_dev $2`
+        [[ -z $dev ]] && echo "Invalid device" && exit 1
+        mac=${devices[$dev]}
+        connected=`bluetoothctl info | grep "$dev" -A 8 | grep "Connected" | awk '{ print $2 }'`
+        if [[ $connected == 'yes' ]]; then
+            bluetoothctl disconnect $mac || exit 1
+        else
+            bluetoothctl connect $mac || exit 1
+        fi
+        ;;
+    add | a)
+        [[ -z $2 || -z $3 ]] && echo "Usage: bt add [name] [mac]" && exit 1
+        echo "$2 $3" >> "$DEVFILE" && echo "Sucessfully added $2 ($3) to the list of devices"
+        ;;
+    remove | r)
+        [[ -z $2 ]] && echo "Usage: bt remove [name]" && exit 1
+        ! has_dev $2 && echo "Invalid device \"$2\"" && exit 1
+        sed -i "/^$2 /d" "$DEVFILE"
+        ;;
+    menu | m)
+        echo TODO: launch rofi
+        ;;
+    *)
+        echo "Usage: bt [connect | disconnect | add [name] [mac] | remove [name]]"
         ;;
 esac
-
-if [ -z $2 ]
-then
-    connected=`bluetoothctl info | grep "$dev" -A 8 | grep "Connected" | awk '{ print $2 }'`
-	if [[ $connected == 'yes' ]]
-	then
-		bluetoothctl disconnect $dev
-	else
-		bluetoothctl connect $dev
-	fi
-else
-	case $2 in
-		c)
-			bluetoothctl connect $dev
-			;;
-		d)
-			bluetoothctl disconnect $dev
-			;;
-	esac
-fi
-
-if [ $1 = "wacom" ]
-then
-    config-wacom
-fi
